filter:
    excluded_paths:
        - 'js/vendor/*'
        - 'js/public/*'
        - 'js/tests/stubs/*'
        - 'l10n/*'
        - 'tests/*'

imports:
    - javascript
    - php

tools:
    # external coverage is broken
    #external_code_coverage: true
